
# .goreleaser.yml
builds:
- env: 
  - CGO_ENABLED=0
  - gtags={{ .Env.GITHUB_TAGS }}
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  main: ./cmd/manager/main.go  
dockers:
- image_templates: [gtags]
  dockerfile: fast.Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/filipcirtog/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/filipcirtog/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates: ["{{ .Env.GITHUB_TAG }}"]
  goarch: arm64
  dockerfile: fast.Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/filipcirtog/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/filipcirtog/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
- name_template: ghcr.io/filipcirtog/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/filipcirtog/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/filipcirtog/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/filipcirtog/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/filipcirtog/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/filipcirtog/{{ .ProjectName }}:{{ .Version }}-arm64v8
