# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/manager/main.go
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
archives:
- format: zip

  # Include version in archive only for release builds and not for snapshot builds.
  # Snapshot archives must have a stable file name such that the artifacts in the nightly
  # release are automatically overwritten. If the snapshot version is included in the
  # file name then additional logic to clean up older builds would be needed.
  name_template: 'mongodb-atlas-kubernetes-operator-{{ if not .IsSnapshot }}{{ .Version }}_{{ end }}{{ .Os }}_{{ .Arch }}'
  
dockers:
  - image_templates:
      - "{{ if not .IsSnapshot }}{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-arm64{{ end }}"
    goarch: arm64
    dockerfile: fast.Dockerfile
    use: buildx
  - image_templates:
      - "{{ if not .IsSnapshot }}{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-amd64{{ end }}"
    goarch: amd64
    dockerfile: fast.Dockerfile
    use: buildx
  - image_templates:
      - "{{ if not .IsSnapshot }}quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-arm64{{ end }}"
    goarch: arm64
    dockerfile: fast.Dockerfile
    use: buildx
  - image_templates:
      - "{{ if not .IsSnapshot }}quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-amd64{{ end }}"
    goarch: amd64
    dockerfile: fast.Dockerfile
    use: buildx
  - image_templates:
      - "{{ if not .IsSnapshot }}quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-certified-arm64{{ end }}"
    goarch: arm64
    dockerfile: fast.Dockerfile
    use: buildx
  - image_templates:
      - "{{ if not .IsSnapshot }}quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-certified-amd64{{ end }}"
    goarch: amd64
    dockerfile: fast.Dockerfile
    use: buildx
  - image_templates:
      - "{{ if .IsSnapshot }}ghcr.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-arm64{{ end }}"
    goarch: arm64
    dockerfile: fast.Dockerfile
    use: buildx
  - image_templates:
      - "{{ if .IsSnapshot }}ghcr.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-amd64{{ end }}"
    goarch: amd64
    dockerfile: fast.Dockerfile
    use: buildx

docker_manifests:
  - name_template: "{{ if not .IsSnapshot }}{{.Env.REPOSITORY}}:{{ .Env.VERSION }}{{ end }}"
    image_templates:
      - "{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-arm64"
      - "{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-amd64"
  - name_template: "quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}{{ end }}"
    image_templates:
      - "quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-arm64"
      - "quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-amd64"
  - name_template: "{{ if not .IsSnapshot }}quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-certified{{ end }}"
    image_templates:
      - "quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-certified-arm64"
      - "quay.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-certified-amd64"
  - name_template: "{{ if .IsSnapshot }}ghcr.io/{{.Env.REPOSITORY}}{{ .Env.VERSION }}{{ end }}"
    image_templates:
      - "ghcr.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-arm64"
      - "ghcr.io/{{.Env.REPOSITORY}}:{{ .Env.VERSION }}-amd64"


release:
  draft: true
  header: |
    # MongoDB Atlas Operator x.y.z

    > See the internal "Release Note Authoring Guidance" Wiki page for details

    ## Warnings

    > Put here anything that user needs to know to use this version. In most cases, this section will be empty and removed.

    ## New features, improvements and bug fixes

    > Mention shipped things in this particular order. In any improvements need migration guides, please include them here as well.

    ## Deprecations and removals

    > First deprecations and then removals.

    Images can be found at: https://quay.io/mongodb/mongodb-atlas-kubernetes-operator

    Supported Kubernetes versions: `e.g. 1.27-1.29`
    Supported OpenShift versions: `e.g 4.14`
