name: Check Licenses

on:
  workflow_call:

jobs:
  check-licenses:
    name: Check Licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
            nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Cache Nix store
        id: cache-nix
        uses: actions/cache@v3
        with:
              path: |
                /nix/store
                ~/.cache/nix
              key: ${{ runner.os }}-nix-${{ hashFiles('shell.nix') }}
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum', '**/go.mod') }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          cache: false

      - run: go version

      - name: Run testing
        run: nix-shell --run "make check-licenses"
