name: Check Licenses

on:
  workflow_call:

jobs:
  check-licenses:
    name: Check Licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Restore Nix store from cache
        uses: actions/cache@v4
        id: cache-nix-store
        with:
          path: /nix/store
          key: nix-store-${{ runner.os }}-${{ hashFiles('shell.nix') }}
          restore-keys: |
            nix-store-${{ runner.os }}-

      - name: Restore Nix profiles from cache
        uses: actions/cache@v4
        id: cache-nix-profiles
        with:
          path: /nix/var/nix/profiles
          key: nix-profiles-${{ runner.os }}
          restore-keys: |
            nix-profiles-${{ runner.os }}

      - name: Install Nix shell
        if: steps.cache-nix-store.outputs.cache-hit != 'true' || steps.cache-nix-profiles.outputs.cache-hit != 'true'
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum', '**/go.mod') }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          cache: false

      - run: go version

      - name: Run testing
        run: nix-shell --run "make check-licenses"
