# Check for every push
name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          cache: false
        # Cache the Nix installation
      - name: Cache Nix installation
        id: cache-nix-install
        uses: actions/cache@v3
        with:
          path: /nix
          key: ${{ runner.os }}-nix-install
          restore-keys: |
            ${{ runner.os }}-nix-install

      # Install Nix if not cached
      - name: Install Nix
        if: steps.cache-nix-install.outputs.cache-hit != 'true'
        run: |
          curl -L https://nixos.org/nix/install | sh
          . ~/.nix-profile/etc/profile.d/nix.sh
      - name: Cache Nix store
        uses: actions/cache@v3
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: ${{ runner.os }}-nix-${{ hashFiles('shell.nix') }}

      - name: lint
        run: nix-shell --run 'make lint'

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2

      - name: Run govulncheck
        run: nix-shell --run 'make vulncheck'
