# Check for every push
name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          cache: false

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
    
      - name: Cache Nix store
        id: cache-nix
        uses: actions/cache@v3
        with:
            path: |
              /nix/store
              ~/.cache/nix
            key: ${{ runner.os }}-nix-${{ hashFiles('shell.nix', 'default.nix') }}
            restore-keys: |
              ${{ runner.os }}-nix-

      - name: lint
        run: nix-shell --run 'make lint'

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2

      - name: Run govulncheck
        run: nix-shell --run 'make vulncheck'
