# Check for every push
name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          cache: false

      - name: Restore and save Nix store
        uses: ./.
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('**/shell.nix') }}
          purge: true
              # purge all versions of the cache
          purge-prefixes: build-${{ runner.os }}-
              # created more than 0 seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
              # except the version with the `primary-key`, if it exists
          purge-primary-key: never
      - name: lint
        run: nix-shell --run 'make lint'

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2

      - name: Run govulncheck
        run: nix-shell --run 'make vulncheck'
