name: Test

on:
  schedule:
    - cron: '0 0 * * 1-5' # Run a nightly test 
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft, labeled, unlabeled]
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
  merge_group:
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    # Contributions do NOT run any testing by default, a label is needed to allow testing
    if: |
      github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name ||
      contains(github.event.pull_request.labels.*.name, 'safe-to-test') ||
      contains(github.event.pull_request.labels.*.name, 'cloud-tests') ||
      contains(github.event.pull_request.labels.*.name, 'retest')
    steps:
      - name: allowed message
        run: echo "Allowed to run tests"
      
      - name: Restore Nix store from cache
        uses: actions/cache@v4
        id: cache-nix-store
        with:
          path: /nix/store
          key: nix-store-${{ runner.os }}-${{ hashFiles('shell.nix') }}
          restore-keys: |
            nix-store-${{ runner.os }}-

      - name: Restore Nix profiles from cache
        uses: actions/cache@v4
        id: cache-nix-profiles
        with:
          path: /nix/var/nix/profiles
          key: nix-profiles-${{ runner.os }}
          restore-keys: |
            nix-profiles-${{ runner.os }}

      - name: Install Nix shell
        if: steps.cache-nix-store.outputs.cache-hit != 'true' || steps.cache-nix-profiles.outputs.cache-hit != 'true'
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: allowed message
        run: echo "Allowed to run tests"

  lint:
    needs:
      - run-tests
    uses: ./.github/workflows/lint.yaml

  validate-manifests:
    needs:
      - run-tests
    uses: ./.github/workflows/validate-manifests.yml
  
  unit-tests:
    needs:
      - run-tests
    uses: ./.github/workflows/test-unit.yml

  check-licenses:
    needs:
      - run-tests
    uses: ./.github/workflows/check-licenses.yml
  
  cloud-tests-filter:
    needs:
      - run-tests
    uses: ./.github/workflows/cloud-tests-filter.yml

  cloud-tests:
    needs:
      - lint
      - unit-tests
      - validate-manifests
      - check-licenses
      - cloud-tests-filter
    if: (github.event_name == 'merge_group' || needs.cloud-tests-filter.outputs.run-cloud-tests == 'true')
    uses: ./.github/workflows/cloud-tests.yml
    secrets: inherit
    with:
      forked: ${{ github.event.repository.full_name != github.event.pull_request.head.repo.full_name }}
