name: Validate Manifests

on:
  workflow_call:

jobs:
  validate-manifests:
    name: Validate Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Restore and save Nix store
        uses: ./.
        with:
            primary-key: build-${{ runner.os }}-${{ hashFiles('**/shell.nix') }}
            paths: |
              ~/.npm
            # do purge caches
            purge: true
            # purge all versions of the cache
            purge-prefixes: build-${{ runner.os }}-
            # created more than 0 seconds ago relative to the start of the `Post Restore` phase
            purge-created: 0
            # except the version with the `primary-key`, if it exists
            purge-primary-key: never
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum', '**/go.mod') }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          cache: false

      - name: Install dependencies
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Run testing
        run: nix-shell --run 'make validate-manifests'
