name: Validate Manifests

on:
  workflow_call:

jobs:
  validate-manifests:
    name: Validate Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Cache Nix store
        id: cache-nix
        uses: actions/cache@v4
        with:
              path: |
                /nix/store
                ~/.cache/nix
              key: ${{ runner.os }}-nix-${{ hashFiles('shell.nix') }}
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum', '**/go.mod') }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          cache: false

      - name: Install dependencies
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Run testing
        run: nix-shell --run 'make validate-manifests'
